### ISSUE TITLE
[FR] Docker image on Dockerhub?

### ISSUE THREAD

**Issue by Hukuma1** [runcitadel/citadel#15]
One of my issues with installing something like Umbrel is that I wanted to put it on an existing machine with Docker (my NAS that's already running multiple services to be specific). I know there's a guide to running it on a generic Linux machine (just like Citadel has). But to onboard a whole bunch of new users, could this be streamlined further so people can simply drop in Docker Compose stack into their setups?

This cuts out the friction of making a custom Docker container to start with Ubuntu and then manually trying to install Citadel into it. And no dependency update worries. It also makes it way easier to migrate the blockchain as files can easily be pointed to an SMB share or the like.

Something like:
```
version: "3"
services:
  citadel-btc:
    container_name: citadel-btc
    image: citadelrepo/citadel-btc
    ports:
      - 8333:8333/tcp
      - 9735:9735/tcp
    restart: unless-stopped
    volumes:
      - /local-path-to-bitcoin-blockchain:/btcblockchain
      - /local-path-to-config:/config
```
